// Use a disposable history DB; see docs/phase4-history.md.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const assert = require("node:assert/strict");
const fs = require("node:fs"), os = require("node:os"), path = require("node:path");
const base = process.env.FORTUNE_UI_URL || "http://127.0.0.1:3000";
(async () => {
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),"fortune-history-ui-"));
 const browser=await chromium.launch({channel:"msedge",headless:true});
 const reports=[],errors=[];
 try {
  for (const [device,width,height] of [["PC",1280,900],["mobile",375,812]]) {
   const page=await browser.newPage({viewport:{width,height}});
   page.on("pageerror",e=>errors.push(e.message));
   const surname="画面試験"+device+Date.now();
   const fillNew=async()=> {
    await page.goto(base,{waitUntil:"networkidle",timeout:60000});
    for (const [label,value] of [["姓",surname],["名","太郎"],["ふりがな（せい）","カタカナABC"],["ふりがな（めい）","たろう"],["生年月日","1988-08-12"],["出生時刻","09:00"],["鑑定日","2026-10-01"]])
     await page.getByLabel(label,{exact:true}).fill(value);
    await page.getByLabel("出生地").selectOption("東京都");
    await page.getByLabel("性別").selectOption("男性");
   };
   const calculate=async()=> {
    const pending=page.waitForResponse(r=>r.url().endsWith("/api/fortune") && r.request().method()==="POST");
    await page.getByRole("button",{name:"鑑定結果を表示する",exact:true}).click();
    let response;
    try { response=await pending; } catch(error) {
      console.log("FORM DEBUG",await page.locator("form").innerText());
      await page.screenshot({path:path.join(directory,device+"-failure.png"),fullPage:true});
      console.log("DEBUG DIRECTORY",directory); throw error;
    }
    assert.equal(response.status(),200);
    await page.waitForURL("**/result");await page.locator(".gogyoFigure").first().waitFor();
    return response.json();
   };
   const memo=()=>page.getByLabel("鑑定者用メモの自由記入欄");
   const openMemo=async()=>page.locator("#memo").evaluate(e=>{e.open=true;});
   const save=async()=> {
    const pending=page.waitForResponse(r=>r.url().endsWith("/api/history") && r.request().method()==="POST");
    await page.getByRole("button",{name:"鑑定結果を保存",exact:true}).click();
    const response=await pending,body=await response.json();
    assert.equal(response.status(),200,JSON.stringify(body));
    await page.waitForFunction(()=>document.querySelector(".historyControls [role=status]")?.textContent.startsWith("保存済み"));
    return body.data;
   };
   const layout=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth)<=width,"page overflow");
   await fillNew();await calculate();
   assert.equal(await page.locator(".historyControls [role=status]").textContent(),"未保存");
   assert.equal(await page.locator(".gogyoVariant").nth(1).locator(".gogyoVariantContext").textContent(),"鑑定年：丙午");
   assert.ok(await page.getByRole("heading",{name:"本来の自分らしさ",exact:true}).count());
   await openMemo();await memo().fill(device+" 初回メモ");
   const initial=await save();
   const snapshotText=await page.locator(".resultStack > .section").allTextContents();
   await page.locator("#gogyo").screenshot({path:path.join(directory,device+"-result.png")});
   let calculationCalls=0;
   await page.route("**/api/fortune",route=>{calculationCalls++;return route.abort();});
   await page.goto(base+"/history/"+initial.id,{waitUntil:"domcontentloaded"});
   await page.locator(".gogyoFigure").first().waitFor();
   assert.deepEqual(await page.locator(".resultStack > .section").allTextContents(),snapshotText);
   assert.equal(calculationCalls,0);
   await layout();await openMemo();assert.equal(await memo().inputValue(),device+" 初回メモ");
   let patches=0;page.on("request",r=>{if(r.method()==="PATCH")patches++;});
   await memo().fill(device+" 更新メモ");
   assert.equal(await page.locator(".historyControls [role=status]").textContent(),"未保存の変更あり");
   assert.equal(patches,0);
   const patchResponse=page.waitForResponse(r=>r.url().endsWith("/memo") && r.request().method()==="PATCH");
   await page.getByRole("button",{name:"メモの変更を保存",exact:true}).click();
   assert.equal((await (await patchResponse).json()).data.memo,device+" 更新メモ");
   await page.waitForFunction(()=>document.querySelector(".historyControls [role=status]")?.textContent.startsWith("保存済み"));
   assert.equal(patches,1);
   await page.reload({waitUntil:"domcontentloaded"});await page.locator(".gogyoFigure").first().waitFor();
   await openMemo();assert.equal(await memo().inputValue(),device+" 更新メモ");
   await page.unroute("**/api/fortune");
   await page.getByRole("button",{name:"この人を再鑑定",exact:true}).click();
   await page.getByRole("button",{name:"過去履歴を引き継いで再鑑定",exact:true}).click();
   await page.waitForURL(base+"/");
   const today=new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo"}).format(new Date());
   assert.equal(await page.getByLabel("鑑定日",{exact:true}).inputValue(),today);
   assert.equal(await page.getByLabel("姓",{exact:true}).inputValue(),surname);
   assert.equal(await page.getByLabel("ふりがな（せい）",{exact:true}).inputValue(),"カタカナABC");
   await calculate();await openMemo();
   assert.equal(await memo().inputValue(),"");
   assert.ok((await page.getByLabel("過去の鑑定メモ",{exact:true}).textContent()).includes(device+" 更新メモ"));
   await memo().fill(device+" 同グループの今回だけ");
   const second=await save();
   assert.equal(second.person_id,initial.person_id);assert.equal(second.group_id,initial.group_id);
   assert.notEqual(second.id,initial.id);assert.equal(second.source_reading_id,initial.id);
   assert.equal(second.memo,device+" 同グループの今回だけ");
   await page.getByRole("button",{name:"この人を再鑑定",exact:true}).click();
   await page.getByRole("button",{name:"過去履歴を引き継がず新規鑑定",exact:true}).click();
   await page.waitForURL(base+"/");await calculate();await openMemo();
   assert.equal(await page.getByLabel("過去の鑑定メモ",{exact:true}).count(),0);
   await memo().fill(device+" 新グループメモ");
   const third=await save();
   assert.equal(third.person_id,initial.person_id);assert.notEqual(third.group_id,initial.group_id);
   await fillNew();await page.getByRole("button",{name:"鑑定結果を表示する",exact:true}).click();
   const candidate=page.getByLabel("同一人物候補確認",{exact:true});
   await candidate.waitFor();assert.equal(await candidate.locator("article").count(),1);
   await layout();await candidate.screenshot({path:path.join(directory,device+"-candidate.png")});
   await page.getByRole("button",{name:"別人として登録する",exact:true}).click();
   await calculate();const other=await save();assert.notEqual(other.person_id,initial.person_id);
   await fillNew();await page.getByRole("button",{name:"鑑定結果を表示する",exact:true}).click();
   await candidate.waitFor();assert.equal(await candidate.locator("article").count(),2);
   const target=candidate.locator("article").filter({has:page.getByRole("button",{name:/グループ2/})});
   assert.equal(await target.count(),1);
   await target.getByRole("button",{name:/同一人物として、過去の鑑定履歴を引き継ぐ/}).first().click();
   await calculate();await openMemo();assert.ok((await page.getByLabel("過去の鑑定メモ",{exact:true}).textContent()).includes("メモ"));
   await page.goto(base+"/history",{waitUntil:"domcontentloaded"});
   await page.waitForFunction(()=>!document.querySelector(".historySearch button")?.disabled);
   await page.getByLabel("キーワード",{exact:true}).fill(surname);
   await page.getByRole("button",{name:"検索",exact:true}).click();
   await page.waitForFunction(()=>!document.querySelector(".historySearch button")?.disabled);
   const entries=page.locator(width>760?".historyDesktop tbody tr":".historyMobile .historyCard");
   assert.equal(await entries.count(),4);
   await layout();await page.screenshot({path:path.join(directory,device+"-list.png"),fullPage:true});
   await page.getByLabel("キーワード",{exact:true}).fill("カタカナABC");
   // The original and rerun dates differ after Oct 1. Include both dates;
   // retain the same >=4 search assertion and each snapshot's saved date.
   const range=["2026-10-01",today].sort();
   await page.getByLabel("鑑定日（開始）",{exact:true}).fill(range[0]);
   await page.getByLabel("鑑定日（終了）",{exact:true}).fill(range[1]);
   await page.getByRole("button",{name:"検索",exact:true}).click();
   await page.waitForFunction(()=>!document.querySelector(".historySearch button")?.disabled);
   assert.ok(await entries.count()>=4);
   const first=entries.filter({has:page.locator('a[href="/history/'+other.id+'"]')});
   assert.equal(await first.count(),1);
   await first.getByRole("button",{name:/のメニュー/}).click();
   await first.getByRole("button",{name:"削除",exact:true}).click();
   const dialog=page.getByRole("dialog");await dialog.waitFor();
   await page.screenshot({path:path.join(directory,device+"-delete.png"),fullPage:true});
   await dialog.getByRole("button",{name:"キャンセル",exact:true}).click();assert.equal(await dialog.count(),0);
   await first.getByRole("button",{name:/のメニュー/}).click();
   await first.getByRole("button",{name:"削除",exact:true}).click();
   const deletion=page.waitForResponse(r=>r.url().endsWith("/"+other.id) && r.request().method()==="DELETE");
   await dialog.getByRole("button",{name:"削除する",exact:true}).click();assert.equal((await deletion).status(),200);
   await page.waitForFunction(id=>!document.querySelector('a[href="/history/'+id+'"]'),other.id);
   await page.goto(base+"/history/"+other.id,{waitUntil:"domcontentloaded"});await page.locator("p[role=alert]").waitFor();
   assert.ok((await page.locator("p[role=alert]").textContent()).includes("見つかりません"));
   const original=(await (await page.request.get(base+"/api/history/"+initial.id)).json()).data;
   assert.equal(original.memo,device+" 更新メモ");assert.deepEqual(original.result_snapshot,initial.result_snapshot);
   reports.push({device,width,scenarios:14,initial:initial.id,second:second.id,third:third.id,calculationCalls});
   await page.close();
  }
  assert.deepEqual(errors,[]);console.log(JSON.stringify({pass:true,reports,errors,directory},null,2));
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
